### ISSUE TITLE
bug: always-build-MitkTestingHelper-module

### ISSUE THREAD

**Issue by huwqchn** [MITK/MITK#282] opened 2024-05-24 02:15 UTC
The MitkTestingHelper currently is only build if BUILD_TESTING is ON and if MITK_USE_CppUnit is set to 1 which is the case if BUILD_TESTING is ON or MITK_USE_BLUEBERRY is ON.

However, the MitkTestingHelper should also build if BUILD_TESTING is OFF because it is potentially useful for external projects.

```
23>-- The following features have been disabled:
23>
23> * MitkFileFormatConverter, (missing dependencies: MitkTestingHelper)
23> * MitkImageResampler, (missing dependencies: MitkTestingHelper)
23> * MitkCopyGeometry, (missing dependencies: MitkTestingHelper)
23> * MitkDiffusionDICOMLoader, (missing dependencies: MitkTestingHelper)
23> * MitkShToOdfImage, (missing dependencies: MitkTestingHelper)
23> * MitkDImp, (missing dependencies: MitkTestingHelper)
23> * MitkDReg, (missing dependencies: MitkTestingHelper)
23> * MitkFiberScreenshot, (missing dependencies: MitkTestingHelper)
23> * MitkPeakExtraction, (missing dependencies: MitkTestingHelper)
23>
```
I am experiencing an issue when building MITK with the extension directory MITK-Diffusion. Specifically, I encounter a problem with MitkTestingHelper being missing.

I have selected the BUILD_TESTING option, but after clicking configure, this option gets deselected automatically. I am unsure how to proceed with building MitkTestingHelper.

Could you please provide guidance on how to resolve this issue?

Thank you for your assistance.

**Comment by kislinsk** [comment] 2024-05-27 12:30
Hi and thanks for the report!

@peterneher Do you use any functionality of the MitkTestingHelper module outside of tests and/or do you explicitly disable MITK_BUILD_TESTING in MITK-Diffusion?

Is there any functionality that should be moved into a generally available module so it can be used outside of testing? Currently I see three classes in MitkTestingHelper:

- InteractionTestHelper
- RenderingTestHelper
- Generator functions for test images

**Comment by peterneher** [comment] 2024-06-04 07:31
I use mitk::RenderingTestHelper in some of the command line apps. But I never had issues with the disabled MITK_BUILD_TESTING. Which build configuration are you using, @huwqchn ?

**Comment by huwqchn** [comment] 2024-06-04 07:35
> I use mitk::RenderingTestHelper in some of the command line apps. But I never had issues with the disabled MITK_BUILD_TESTING. Which build configuration are you using, @huwqchn ?

I had an issue when building MITK with the extension directory MITK-Diffusion. but building with MITK-ProjectTemplate is fine.

**Comment by peterneher** [comment] 2024-06-04 07:41
so this is solved?

**Comment by huwqchn** [comment] 2024-06-04 07:45
> so this is solved?

I still can't build mitk-diffusion successfully，BUILD_TESTING option will deselected automatically

**Comment by peterneher** [comment] 2024-06-04 07:48
which build configuration are you selecting when building MITK Diffusion?

**Comment by peterneher** [comment] 2024-06-04 07:49
in any case, a workaround is to select the "custom" build config and manually enable BUILD_TESTING again. then it should not be disabled automatically. neverthelese, for me to reproduce the issue, it would be important to know which build config you used in the first place.

**Comment by huwqchn** [comment] 2024-06-04 08:06
<img width="1262" alt="image" src="https://github.com/MITK/MITK/assets/12139734/120df479-3441-485e-a95e-7acd7f2148b4">

![image](https://github.com/MITK/MITK/assets/12139734/dddb7a80-180a-4403-971e-3a78189d1e0e)

![image](https://github.com/MITK/MITK/assets/12139734/e81869c4-8c26-4965-b55a-a71098b476c6)

![image](https://github.com/MITK/MITK/assets/12139734/e44f2a5f-72aa-463b-9390-f864f3f8070d)

![image](https://github.com/MITK/MITK/assets/12139734/54c793ad-46b7-4964-9927-14cc4257e579)

![image](https://github.com/MITK/MITK/assets/12139734/33726831-a93e-4d12-9104-1f94a9a8d964)

![image](https://github.com/MITK/MITK/assets/12139734/8c6f65be-8bf2-4728-bfe2-76a1e95f7ad4)

![image](https://github.com/MITK/MITK/assets/12139734/e062d381-8f28-4dbf-9ce8-46368d5e461f)

![image](https://github.com/MITK/MITK/assets/12139734/8a6294e3-042c-4f19-bdee-ce1bfcdbf339)

![image](https://github.com/MITK/MITK/assets/12139734/0f5ac3cf-632d-4a1b-86ff-3e8890edccb9)

![image](https://github.com/MITK/MITK/assets/12139734/9356b7d5-8e88-4d4e-9651-bda2bb7e1328)

![image](https://github.com/MITK/MITK/assets/12139734/1e8eda3e-68da-4aae-b31a-c64c5a845020)

https://github.com/MITK/MITK/assets/12139734/c08a5715-5180-4af9-8ff0-55a08a911329

I hope this helps

**Comment by peterneher** [comment] 2024-06-04 08:17
are you working on the current master?

and are you manually enabling/disabling other options, or are you just setting the build config to DiffusionRelease and start the build?

**Comment by huwqchn** [comment] 2024-06-04 08:23
I am working on master both mitk and mitk-diffusion, I just follow mitk-diffusion doc, select DiffusionRelease and setting opencv_dir,

**Comment by peterneher** [comment] 2024-06-04 08:24
thank you! trying to reproduce the issue now

**Comment by peterneher** [comment] 2024-06-04 08:53
I just pushed a fix to the diffusion repo. Could you check if your build works now after updating your master?

**Comment by kislinsk** [comment] 2024-06-10 12:26
Seems to be resolved and closed for inactivity. Thank you, Peter! :)

**Closed by kislinsk** 2024-06-10 12:26 UTC
